variables:
  - group: Name.VariableGroup.GlobalVars
  
  - name: env_variable
    value: 'p'  
  - name: enviroment
    value: 'p'   
  - name: SubscriptionId
    value: ''
  - name: AzureSubscription
    value: ''    
  - name: ServicePrincipalGroupName
    value: ''     

  - name: ResourceGroupName
    value:         
  - name: SqlServerName
    value: ''
  - name: StorageAccountName
    value: ''
  - name: ApplicationInsightsName
    value: ''
  - name: AppServiceName 
    value: 'blah-p-$(functionPartialName)-func'    
